# Advanced Methods in Text Analytics

## Basic Python Tutorial

* This is aimed at students in data science and similar fields.
* It is:
    * An introduction to Python as a programming language.
    * An introduction to some important Python libraries for data science.
* This is not:
    * An introduction to programming.
    * A comprehensive introduction to Python (for that, see 
    [here](https://www.w3schools.com/python/)).
    * Aimed at computer scientists.
* Python has nice guides for common practices.
    * E.g. [PEP8](https://peps.python.org/pep-0008/)

## Variables


### Basic Data Types

* Python is strong, but dynamically typed
* Strong: variables do have types
* Dynamic: types are determined at runtime, not at compile time

In [2]:
# note that we don't specify types explicitly (because of dynamic typing)

# ints and floats
a = 12
b = 12.0

# strings
c = "This is 'a' string"
d = 'This is also a string, useful for "quotation marks"'

# booleans
e = True
f = False
# g = false  # throws error, why?

In [3]:
# the print function (useful for debugging)
print("Variable a: {}  (should be an int)".format(a))
print("Variable b: {} (should be a float)".format(b))
print()
print("Variable c: {}".format(c))
print("Variable d: {}".format(d))
print()
print("Variable e: {}  (should be a boolean)".format(e))
print("Variable f: {} (should be a boolean)".format(f))

Variable a: 12  (should be an int)
Variable b: 12.0 (should be a float)

Variable c: This is 'a' string
Variable d: This is also a string, useful for "quotation marks"

Variable e: True  (should be a boolean)
Variable f: False (should be a boolean)


In [4]:
# we can check a variable's type with the type() function
print(type(a))
print(type(b))
print()
print(type(c))
print(type(d))
print()
print(type(f))
print(type(f))

<class 'int'>
<class 'float'>

<class 'str'>
<class 'str'>

<class 'bool'>
<class 'bool'>


In [6]:
# you can also use the isinstance() function
if isinstance(a, int):
    print("Success")

Success


### Collections

In [7]:
# lists
first_list = ["a", 2, True]         # mixed types in elements
second_list = ["d", ["another", "list"]]  # can include other lists

print("LISTS")
print(first_list)
print(second_list)

# sets
first_set = {1, 2, 2, 3}  # check the output! is it the same?
second_set = {"this", "is", "another", "set"}  # is the output order the same?
third_set = {"mixed", "types", 2}  # mixed types 

print()
print("SETS")
print(first_set)
print(second_set)
print(third_set)

# tuples
first_tuple = (1, 2, 2, 3)
second_tuple = ("mixed", "types", 2)

print()
print("TUPLES")
print(first_tuple)
print(second_tuple)

# dictionaries
first_dict = {"key1": 1, "key2": 2}
second_dict = {"key3": 3, 4: "key4"}     # keys, values need not be same type

print()
print("DICTS")
print(first_dict)
print(second_dict)

if "a" in first_list:
    print("Found it!")

LISTS
['a', 2, True]
['d', ['another', 'list']]

SETS
{1, 2, 3}
{'this', 'is', 'set', 'another'}
{'types', 2, 'mixed'}

TUPLES
(1, 2, 2, 3)
('mixed', 'types', 2)

DICTS
{'key1': 1, 'key2': 2}
{'key3': 3, 4: 'key4'}
Found it!


* Two main differences between different types of collections
    * Efficiency, e.g. retrieval from list is much slower than set/dict
    * Mutability, you can change lists, sets and dicts, but not tuples.

In [18]:
some_list = range(1, 10000000)
some_set = set(some_list)
if 999 in some_set:
    print("Found it!")

Found it!


### Operations with Collections

In [21]:
# some examples

# append
print(first_list)
first_list.append("new element")
print(first_list)

# extend
print()
first_list.extend(second_list)
print(first_list)

# insert
print()
first_list.insert(0, "new first element")
print(first_list)

# len
print()
print("Length of 'first_list': ", len(first_list))

# sort
# print(first_list.sort())  # throws error if incomparable types

['a', 'new first element', 'new first element', 2, True, 'new element', 'd', ['another', 'list'], 'new element', 'd', ['another', 'list']]
['a', 'new first element', 'new first element', 2, True, 'new element', 'd', ['another', 'list'], 'new element', 'd', ['another', 'list'], 'new element']

['a', 'new first element', 'new first element', 2, True, 'new element', 'd', ['another', 'list'], 'new element', 'd', ['another', 'list'], 'new element', 'd', ['another', 'list']]

['new first element', 'a', 'new first element', 'new first element', 2, True, 'new element', 'd', ['another', 'list'], 'new element', 'd', ['another', 'list'], 'new element', 'd', ['another', 'list']]

Length of 'first_list':  15


## Functions

* *Goal:* encapsulate code, the DRY principle

In [ ]:
# example of basic function (including docstrings!)
def some_basic_function(some_number):
    """ Returns some_number unchanged. If some_number is an int, also returns
    its square.

    Args:
        some_number (int): Squares a given integer
    """

    if isinstance(some_number, int):
        return some_number, some_number ** 2
    else:
        return some_number

arg1 = 3
arg2 = 3.0

# test it!
output1 = some_basic_function(arg1)
print(output1)      # note the type of output

output2 = some_basic_function(arg2)
print()
print(output2)

# unpacking
number, square = some_basic_function(arg1)
print()
print(number)
print(square)


(3, 9)

3.0

3
9


## Assignment by Copying vs by Reference

In [23]:
foo = "example of a string"
bar = foo

print(bar)

example of a string


In [24]:
# now modify bar
bar = "changed string"

print(bar)

changed string


In [25]:
# what is now the value of foo?
print(foo)  # should not have changed

example of a string


In [26]:
# let's try with a list
foo_list = ["a", "b", "c"]
bar_list = foo_list

print(bar_list)

['a', 'b', 'c']


In [27]:
# now modify bar_list
bar_list.append("d")

print(bar_list)

['a', 'b', 'c', 'd']


In [28]:
# what is now the value of foo_list?
print(foo_list)   # should have changed

['a', 'b', 'c', 'd']


* Some assignments are made by copy, as in strings _foo_ and _bar_
* Some assignments are made by reference, as in lists _foo_list_ and _bar_list_
* This is important when writing code in Python!
* Similarly, be careful when passing arguments to functions and modifying their value!

In [30]:
def compute_with_list(some_list):
    """ Function that computes something with some_list

    Args:
        some_list (list): list to compute something with
    """

    # the classic way of thinking
    for element_id in range(len(some_list)):
        element = some_list[element_id]

    # the modern way
    for element in some_list:
        pass

    # the pythonic way
    # note the use of unpacking and enumerate
    for id, element in enumerate(some_list):
        some_list[id] = element * 2

    return some_list

# create some list
my_list = [1, 2, 3]
print("My list BEFORE passing to some function:", my_list)
# pass my list to a function that may do some changes to it
compute_with_list(my_list)
# what happened?
print("My list AFTER passing to some function:", my_list)


My list BEFORE passing to some function: [1, 2, 3]
My list AFTER passing to some function: [2, 4, 6]


* Arguments are passed by reference to functions
* We may want that if we want the function to change our object
* But we may not want some function changes our object!

## Numpy

* Essential [library](https://numpy.org/) (collection of ready-made objects and functions) for scientific computing
* Design based on MatLab
* In some ways similar to using basic Python
* In others, very different from basic Python
* Important understand the differences and make use of them!

### Creating Arrays

In [4]:
# import what we need
import numpy as np
import time

In [32]:
# basic object in numpy: n-dimensional arrays
# can be created from lists
array1D = np.array([1, 2, 3])
array2D = np.array([[1, 2], [3, 4]])
array3D = np.array([[[1, 2,], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

print(array1D)
print("Shape:", array1D.shape)
print()
print(array2D)
print("Shape:", array2D.shape)
print()
print(array3D)
print("Shape:", array3D.shape)

[1 2 3]
Shape: (3,)

[[1 2]
 [3 4]]
Shape: (2, 2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Shape: (3, 2, 2)


In [33]:
# more ways to create arrays
# arange
another_array1D = np.arange(10)
print(another_array1D)

# zeros
another_array2D = np.zeros([3, 3])
print()
print(another_array2D)

# ones
another_array3D = np.ones([3, 3, 3])
print()
print(another_array3D)

[0 1 2 3 4 5 6 7 8 9]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### Indexing Arrays

In [35]:
# This cell was created by Google's Bard (LLM) with the following prompt:
# "Please create some code in Python with basic examples of the various ways to 
# index arrays in numpy, and add brief but explanatory comments where necessary"

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Single array element
# This will print the element at index (0, 0), which is 1.
print('Single array element:', arr[0, 0])  

# Slicing
# This will print the elements from index (0, 0) to index (1, 1), 
# which is the subarray [[1, 2], [4, 5]].
print('Slicing:', arr[0:2, 0:2])  

# Boolean indexing
# This will print the elements in the array that are greater than 3,
# which is [4, 5, 6].
print(arr > 3) # output is boolean array, same size as arr
print('Boolean indexing:', arr[arr > 3])  

# Fancy indexing
# This will print the elements at the indices (0, 1) and (1, 2), 
# which is [2, 6].
print('Fancy indexing:', arr[[0, 1], [1, 2]])  


Single array element: 1
Slicing: [[1 2]
 [4 5]]
[[False False False]
 [ True  True  True]]
Boolean indexing: [4 5 6]
Fancy indexing: [2 6]


In [36]:
# let's elaborate on Bard's output, shall we?
# slicing tells us the range of rows and range of colums to use
# Bard's example
his_array = np.array([[1, 2, 3], [4, 5, 6]])
print("His Array")
print(his_array)
print()
print('Slicing:\n', arr[0:2, 0:2])  
print()

# we can also specify a subset of rows and all columns
print('Slicing:\n', arr[0:2, :])  
print()

# or viceversa
print('Slicing:\n', arr[:, 0:2])  
print()

His Array
[[1 2 3]
 [4 5 6]]

Slicing:
 [[1 2]
 [4 5]]

Slicing:
 [[1 2 3]
 [4 5 6]]

Slicing:
 [[1 2]
 [4 5]]



In [37]:
# boolean indexing can be useful with relevant conditions 
examples = np.array(["a", "b", "c", "d", "f", "g", "h", "i", "j", "k", "m"])
predictions = np.array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1])
positive_class_predictions = predictions[predictions == 1]

print("Predictions")
print(predictions)
print()
print("How many predictions of the positive class?")
print(len(positive_class_predictions))
print()
print("Give me the corresponding examples, please!")
print(examples[predictions == 1])

Predictions
[1 1 1 0 0 0 1 0 0 1 1]

How many predictions of the positive class?
6

Give me the corresponding examples, please!
['a' 'b' 'c' 'h' 'k' 'm']


### Operations with Numpy Arrays

We look at some basic operations here, and leave the more mathematical ones for
later when we look at PyTorch basics.

In [38]:
# many operations are by default applied element-wise
some_array = np.arange(9).reshape([3,3])
print(some_array)

# scalar product
print()
print("Scalar product")
print(some_array * 2)

# scalar product
print()
print("Scalar product")
print(some_array * 3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

Scalar product
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Scalar product
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


Some of the code from the following cells was created by Google's Bard with
the following prompt, which followed the prompt mentioned above:
"Great, now do the same but for basic operations that one can do with numpy 
arrays"

In [39]:
# Arithmetic operations: You can perform arithmetic operations on NumPy arrays, 
# such as addition, subtraction, multiplication, division, and exponentiation. 
# For example:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # Addition
print(arr1 - arr2)  # Subtraction
print(arr1 * arr2)  # Multiplication
print(arr1 / arr2)  # Division
print(arr1 ** 2)    # Exponentiation

# note that operands must satisfy basic operation's constraints, e.g. same shape

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [40]:
# Aggregation operations: These operations calculate summary statistics of the 
# array elements, such as the sum, mean, standard deviation, minimum, and 
# maximum. For example:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))  # Sum of all elements
print(np.mean(arr))  # Mean of all elements
print(np.std(arr))  # Standard deviation of all elements
print(np.min(arr))  # Minimum element
print(np.max(arr))  # Maximum element


15
3.0
1.4142135623730951
1
5


In [41]:
# Comparison operations: You can compare NumPy arrays to each other using the 
# standard comparison operators, such as <, >, ==, !=, <=, and >=. For example:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Check if each element of arr1 is less than the corresponding element of arr2
print(arr1 < arr2)  
# Check if each element of arr1 is equal to the corresponding element of arr2
print(arr1 == arr2)

[ True  True  True]
[False False False]


In [43]:
# Sorting: You can sort a NumPy array, either by the values of the elements or 
# by the indices of the elements. For example:
arr = np.array([3, 1, 2, 5, 4])

print(np.sort(arr))  # Sort the array by the values of the elements
print(np.argsort(arr))  # Sort the array by the indices of the elements

[1 2 3 4 5]
[1 2 0 4 3]


## Why use Numpy? Vectorized Computations

### The simplest example: vector addition

In [44]:
# define function to create two random vectors of given length
def create_vectors(length=5, range_=5):    
    """ 
    Creates two random vectors of size length_ 
    Vector elements are integers in interval [0, range_)
    """
    a = np.random.randint(range_, size=length)
    b = np.random.randint(range_, size=length)
    return a, b 

In [45]:
# define function to naively compute vector addition
def naive_vector_addition(a, b):
    """ Returns addition of input vectors a and b as as a new vector """
    assert len(a) == len(b)
    c = np.copy(a)
    for i in range(len(a)):
        c[i] += b[i]
    return c

In [46]:
# test naive addition
a, b = create_vectors()
naive_output = naive_vector_addition(a, b)
print("a:     ", a)
print("b:     ", b)
print("a + b: ", naive_output)

a:      [3 1 3 3 0]
b:      [2 0 3 2 1]
a + b:  [5 1 6 5 1]


In [48]:
# vectorized addition
def vectorized_addition(a, b):
    """ Returns addition of input vectors a and b as as a new vector """
    assert len(a) == len(b)
    return a + b

In [49]:
# test vectorized addition
vectorized_output = vectorized_addition(a, b)
print("a:     ", a)
print("b:     ", b)
print("a + b: ", vectorized_output)

a:      [3 1 3 3 0]
b:      [2 0 3 2 1]
a + b:  [5 1 6 5 1]


In [50]:
# are outputs the same?
print(naive_output == vectorized_output)

[ True  True  True  True  True]


In [56]:
# why bother then? try different lengths
length = 100000000
a, b = create_vectors(length)
start_time = time.time()
naive_vector_addition(a, b)
end_time = time.time()
print("Naive:       ", end_time - start_time)

start_time = time.time()
vectorized_addition(a, b)
end_time = time.time()
print("Vectorized:   ", end_time - start_time)

Naive:        16.57202696800232
Vectorized:    0.36727094650268555


### A more realistic example

In [59]:
# define function to create random data
def create_data(num_examples=1000, size_=10, range_=5):
    """ 
    Creates random dataset of shape (num_examples, size_) 
    Data is set of integers in interval [0, range_)
    """ 
    return np.random.randint(range_, size=(num_examples, size_))

In [ ]:
# define random linear regression model with naive and vectorized prediction 
# methods
class LRModel():
    """ Linear regression model class """
    def __init__(self, size_=10, range_=5):
        """ 
        Randomly initializes model of given size
        Weights and bias are integers in interval [0, range_)
        """
        self.weights = np.random.randint(range_, size=size_)
        self.bias = np.random.randint(range_, size=1)
        
    def stubborn_predict(self, data):
        """ Naive implementation of applying model to given data """
        predictions = np.zeros(len(data))
        
        # iterate over examples
        # for i in range(len(data)):
        for i in range(n):
            # iterate over features
            for j in range(d):
                predictions[i] += self.weights[j] * data[i, j]
            predictions[i] += self.bias
        return predictions

    def vectorized_predict(self, data):
        """ Vectorized implementation of applying model to given data """
        return np.matmul(data, self.weights) + self.bias

In [60]:
# let's try linear regression on n training examples of size d
# create random data
n = 1000
d = 10
data = create_data(n, d)

# create random model
model = LRModel(d)

In [61]:
# naive prediction
naive_predictions = model.naive_predict(data)
print(naive_predictions.shape)

(1000,)


/tmp/ipykernel_6541/3254483671.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions[i] += self.bias


In [62]:
# vectorized prediction
vectorized_predictions = model.vectorized_predict(data)
print(vectorized_predictions.shape)

(1000,)


In [63]:
# are they the same?
print(naive_predictions == vectorized_predictions)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [67]:
# why bother then?
n = 10000000
d = 10
data = create_data(n, d)
model = LRModel(d)
start_time = time.time()
naive_predictions = model.naive_predict(data)
end_time = time.time()
print("Naive:       ", end_time - start_time)

start_time = time.time()
vectorized_predictions = model.vectorized_predict(data)
end_time = time.time()
print("Vectorized:   ", end_time - start_time)

/tmp/ipykernel_6541/3254483671.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions[i] += self.bias


Naive:        48.8154456615448
Vectorized:    0.12885212898254395


### We cannot avoid all loops...

* Can't avoid looping over epochs
* Can't avoid looping over batches
* Why not? Important things are computed in between (you'll see)
* This does not mean loops aren't taking place, they are but at a lower and more efficient level

### An important way to avoid loops: broadcasting

[Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) fundamentals. Key points:

* Allows operations between arrays of different sizes.
* Dimensions are read from right to left.
* Two dimensions are compatible when they are equal, or one of them is 1, or when one of them is missing.
* Dimensions with size 1 (or missing) are stretched or “copied” to match the other.
* The smaller array is “broadcasted” across the larger array so they have compatible shapes. 
* Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.

In [68]:
x = np.arange(4)
print(x)
print(x.shape)

[0 1 2 3]
(4,)


In [69]:
y = np.ones(5)
print(y)
print(y.shape)

[1. 1. 1. 1. 1.]
(5,)


In [70]:
# error
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [71]:
# reshape into broadcastable shape
x2 = x.reshape(4,1)
print(x2)
print(x2.shape)

[[0]
 [1]
 [2]
 [3]]
(4, 1)


In [72]:
# broadcast! 
# y is size (5), x2 is size (4, 1)
# Comparing from the right, you have 
# (4, 1)
# (   5)
# The rightmost dimensions meet broadcasting requirement.
# So, the single column in x2 is broadcasted across 2nd axis to 
# match the single dimension of y, producing a 4x5 matrix.
# Now we have an intermediate operation of summing row vector y of
# size (5) with matrix of shape (4, 5).
# The operation is then done 4 times, one for each row in x2
# i.e, row vector y is added to each row in this matrix
print(x2 + y)
print((x2 + y).shape)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
(4, 5)


In [73]:
# a more concrete example
mat = np.ones([3, 3])
vec = np.arange(2, 5)

print(mat)
print(mat.shape)
print()
print(vec)
print(vec.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)

[2 3 4]
(3,)


In [74]:
# what happened here? 
# mat was created as a 1x3 vector (missing dim).
# So vec was broadcaster across the leftmost dim of mat (i.e. the rows)
print(mat + vec)
print(mat.shape)
print(vec.shape)

[[3. 4. 5.]
 [3. 4. 5.]
 [3. 4. 5.]]
(3, 3)
(3,)


In [76]:
# Can we broadcast vec in the other dimension of mat?
# Yes! Reshape so rightmost dim is the one broadcasting.
vec2 = vec.reshape(3, 1)
print(mat + vec2)

[[3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]


### Moral of the story

* Learn to code in vectorized form
* Stick to using the efficient operations provided by libraries such as [numpy](https://numpy.org/doc/), [PyTorch](https://pytorch.org/docs/stable/index.html) or [Tensorflow](https://www.tensorflow.org/api_docs) 

## How to Navigate Code

* Learn to use an IDE or editor, such as PyCharm or VSCode, respectively.
* IDEs vs Editors
    * IDEs: heavy but feature-rich, usually easier to configurate, maintain
    * Editors: lightweight but generally more costly to maintain (plugins)
* Why learn about these tools?
    * Coding becomes much more enjoyable.
    * Why? From basic autocomplete, to navigating code easily.
        * "Go to Definition"
        * "Find usages"
        * "Back/Forward"
        * "Refactor"
    * Generally, plugins for everything: git, linting, any language you want.

## Python Distributions

* What are these? 
    * Software bundle that includes Python interpreter, standard library, 
    package manager
* Package managers are essential for installing new libraries for data science
    * PIP: includes Python libraries, recommended for pure Python projects
    * Conda: additionally includes C libraries and executables, recommended for 
    projects requiring different Python versions, complex binary dependencies

## Python Environments

* Super important concept that you want to learn about and use regularly!
* *Python environment:* isolation of a Python interpreter, library and installed 
scripts
* *Why important?* 
    * Different projects may require different libraries, or different versions 
    of the same library, which may not be compatible.
    * Often installing one new library or project may break other existing 
    projects.
    * Creating a new environment for each project solves this annoying issue!
    * I use conda environments, but pip can also be used for this with virtualenv.

## PyTorch

* Python library for deep learning, developed by Facebook.
* Similar to tensorflow, developed by Google.
* Main object in PyTorch: tensors
* Tensors are similar to numpy arrays in many ways.
* But they are different in fundamental ways: 
    1. They support automatic gradient computations (crucial for training 
    models)
    2. They support the use of GPUs for computations (much more efficient)

* To install, go [here](https://pytorch.org/), set the settings to the system 
you have, and run the given command.

In [2]:
import torch

### Tensor Creation

In [5]:
# Again, adapting from Google's Bard. The following prompt did not work:
# "Let's keep going, now basic forms of creating torch tensors"
# So I made it more clear again:
# "Let's keep going. Now create examples in Python for different ways to create 
# tensors with PyTorch. Don't forget to put brief but useful comments for each 
# example"

# This creates a 1D tensor with the same data as the Python list.
list_data = [1, 2, 3]
tensor = torch.tensor(list_data)
print(tensor)

# This creates a tensor with the same data as the NumPy array.
np_array = np.array([1, 2, 3])
tensor = torch.from_numpy(np_array)
print()
print(tensor)

# This creates a 2D tensor with random values.
tensor = torch.rand(3, 2)
print()
print(tensor)

# This creates a 2D tensor with all zeros.
tensor = torch.zeros(3, 2)
print()
print(tensor)

# This creates a 2D tensor with all ones.
tensor = torch.ones(3, 2)
print()
print(tensor)

tensor([1, 2, 3])

tensor([1, 2, 3])

tensor([[0.1325, 0.9660],
        [0.1307, 0.9019],
        [0.8212, 0.2782]])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


### Slicing

In [8]:
# same as numpy
# Prompt: Now please create some basic examples of slicing tensors using PyTorch 
# and please add brief but useful comments to the code.

# Create a 2D tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Slicing by row and column
print(tensor[0, :])  # Get the first row
print(tensor[:, 0])  # Get the first column
print(tensor[1, :])  # Get the second row and all columns

# Slicing by range
print(tensor[0:2, 0:2])  # Get the first two rows and first two columns
print(tensor[1:, :])  # Get all rows and the second column onwards

# Slicing by Boolean condition
print(tensor[tensor > 3])  # Get all elements greater than 3


tensor([1, 2, 3])
tensor([1, 4])
tensor([4, 5, 6])
tensor([[1, 2],
        [4, 5]])
tensor([[4, 5, 6]])
tensor([4, 5, 6])


### Operations with Tensors

In [9]:
# again most operations are element-wise
some_tensor = torch.reshape(torch.arange(9), (3,3))
print(some_tensor)

# scalar addition
print()
print(some_tensor + 3)

# scalar product
print()
print(some_tensor * 3)

# apply some function, again, element-wise
print()
print(torch.sigmoid(some_tensor))

# mean, min, max
print()
print(torch.mean(some_tensor.float(), 0))  # note I had to cast to float
print(torch.min(some_tensor, 1))          # what does this return? See docs!
print(torch.max(some_tensor))

# get basic data type out of tensor
print(torch.max(some_tensor).item())


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])

tensor([[0.5000, 0.7311, 0.8808],
        [0.9526, 0.9820, 0.9933],
        [0.9975, 0.9991, 0.9997]])

tensor([3., 4., 5.])
torch.return_types.min(
values=tensor([0, 3, 6]),
indices=tensor([0, 0, 0]))
tensor(8)
8


In [10]:
# common math operations

# dot product
a = torch.ones(3)
b = torch.tensor([2., 2., 2.])
print(torch.dot(a, b))

# matrix-vector product
print()
c = torch.rand(2, 3)
print(b)
print(c)
print(torch.mv(c, b))

# matrix-matrix product
print()
d = torch.rand(3, 4)
print(c)
print(d)
print(torch.mm(c, d))

# batch matrix-matrix operations 
# multiplies corresponding front slices (dim 0)
print()
e = torch.randn(10, 3, 4)
f = torch.randn(10, 4, 5)
print(torch.bmm(e, f).size())

# useful for things like row-wise dot product of matrices
print()
g = torch.ones(3, 10)
h = torch.add(torch.ones(3, 10), 2)
print(g)
print(h)
print(torch.bmm(g.view(3, 1, 10), h.view(3, 10, 1)))

tensor(6.)

tensor([2., 2., 2.])
tensor([[0.1726, 0.3125, 0.4395],
        [0.2278, 0.1492, 0.1945]])
tensor([1.8491, 1.1429])

tensor([[0.1726, 0.3125, 0.4395],
        [0.2278, 0.1492, 0.1945]])
tensor([[0.0516, 0.8418, 0.6356, 0.4422],
        [0.3086, 0.6824, 0.0314, 0.1303],
        [0.5906, 0.0029, 0.6704, 0.1106]])
tensor([[0.3649, 0.3598, 0.4142, 0.1657],
        [0.1727, 0.2941, 0.2798, 0.1417]])

torch.Size([10, 3, 5])

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])
tensor([[[30.]],

        [[30.]],

        [[30.]]])


In [ ]:
# one ring to rule them all (matmul)

# dot if two vectors as input
a = torch.ones(3)
b = torch.tensor([2., 2., 2.])
print(torch.matmul(a, b))

# matrix-vector if matrix and vector as input
print()
c = torch.rand(2, 3)
print(torch.matmul(c, b))

# matrix-matrix if two matrices as input
print()
d = torch.rand(3, 4)
print(torch.matmul(c, d))

# bmm if two 3-way tensors as input
print()
e = torch.randn(10, 3, 4)
f = torch.randn(10, 4, 5)
print(torch.matmul(e, f).size())

### Broadcasting

* The entire discussion above about vectorized computation and broadcasting 
applies directly to PyTorch.
* In fact, [broadcasting](https://pytorch.org/docs/main/notes/broadcasting.html#broadcasting-semantics) is often part of the documentation of functions in 
PyTorch.

### Numpy Arrays vs PyTorch Tensors

As mentioned before, they are different objects!

In [12]:
from pprint import pprint

last_array = np.arange(9)
last_tensor = torch.arange(9)

# shape
print("SHAPE")
print(last_array.shape)
print(last_tensor.shape)
print(last_tensor.size())

# device
print()
print("DEVICE")
if hasattr(last_array, "device"):
    print(last_array.device)
else:
    print("last_array has no attribute 'device'.")
if hasattr(last_tensor, "device"):
    print(last_tensor.device)

# device
print()
print("GRADIENT")
if hasattr(last_array, "grad"):
    print(last_array.grad)
else:
    print("last_array has no attribute 'grad'.")
if hasattr(last_tensor, "grad"):
    print(last_tensor.grad)
else:
    print("last_tensor has no attribute 'grad'.")


SHAPE
(9,)
torch.Size([9])
torch.Size([9])

DEVICE
last_array has no attribute 'device'.
cpu

GRADIENT
last_array has no attribute 'grad'.
None


## Consulting Documentation

* Every library should be well documented.
* [Numpy](https://numpy.org/doc/stable/index.html) and 
[PyTorch](https://pytorch.org/docs/stable/index.html) certainly are.
* Get used to reading documentation!
* How to consult it? Google, read, test.
* Value of learning the fundamentals? You understand documentation!
* How to think about what you need? Using the library is better than DIY!
    Think about your need, google functions/how to do that.
    Example? The gather function (give you real-life example)